# Generated by Django 4.2.11 on 2024-11-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('RUN', 'Running'), ('PAU', 'Paused'), ('COM', 'Completed')], max_length=50)),
                ('agents', models.ManyToManyField(related_name='campaigns', to='app.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('cost', models.FloatField()),
                ('outcome', models.CharField(max_length=100)),
                ('call_duration', models.FloatField()),
                ('recording', models.FileField(upload_to='recordings/')),
                ('summary', models.TextField()),
                ('transcription', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.campaign')),
            ],
        ),
    ]
