# Generated by Django 4.2.11 on 2024-11-26 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='voice_id',
            field=models.UUIDField(default=uuid.UUID, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('INB', 'Inbound'), ('OBD', 'Outbound')], max_length=50),
        ),
    ]
