# Generated by Django 4.2.11 on 2024-11-26 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agent_voice_id_alter_campaign_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='voice_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
