# Generated by Django 4.2.11 on 2024-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agent_id_alter_campaign_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresult',
            name='recording',
            field=models.URLField(),
        ),
    ]
